; M17-Only Hot-Spot Initialization File

[Repeater]

Callsign = "N0CALL"	; Yea, you need to change this

Module = "H"  ; suggest R for repeater and H for hot-spot, but any uppercase letter will work

RadioTypeIsV3 = false ; set to true if the radio being used with this hot-spot is conforming to V3 of the M17 Spec

CAN = 0  ; Channel Access Number, most will use channel 0

Debug = false

[Modem]

; The device path of the gpio chip
GpioChipDevice = "/dev/gpiochip0"
; The device path and speed used for a UART connection
UartDevice = "/dev/ttyAMA0"
UartBaudRate = 460800

; Default GPIO Pin assignments
; These gpio pins provide basic control of the CC1200
; Uncomment these and reassign, if needed. This would be unusual. 
;BOOT0 = 20
;nRST = 21

; Frequencies are in Hz.
; The CC1200 can only support UHF frequencies
RXFrequency = 446500000
;TXFrequency = 446500000 ; uncomment and set if Tx != Rx

; Automatic frequency control
AFC = true

; Offset is +/- Hz
FreqCorrection = 0

; Power in dBm
TXPower = 10

Debug = false

[Gateway]

EnableIPv4 = true
EnableIPv6 = false

; Set to false if you don't want to hear a warning about linking to a URF module that is not transcoded.
WarnNoTranscoder = true
; Set to false if you don't want to hear a warning about linking to an M17 module that allows encryption.
WarnIfEncrypted = true

; uncomment and set to your choice, if needed
; If you use this, remember that for legacy reflectors,
; you will have to set your radio's destination to this
; designator and module to successfully transmit into the reflector.
;StartupLink = M17-M17 C

; JsonHostPath will be downloaded from hostfiles.refcheck.radio
JsonHostPath = "/home/USER/mspot/M17Hosts.json"
MyHostPath = "/home/USER/mspot/MyHosts.txt"

; This is the database used for the dashboard
DBPath = "/home/USER/mspot/mspot.db"

; folder name where audio files are
; usually this should be absolute path to the folder (begins with '/')
; the audio folder now holds multiple voices!
AudioFolderPath = "/home/USER/mspot/audio/sam"

[Ham-DHT Network]

; booting up the very first time
; Choose a reliable M17 or URF reflector that uses the Ham-DHT nearest to you
Bootstrap = "xrf757.openquad.net"
; a place to save your position in the network. For faster network boot up
DHTSavePath = "/home/USER/mspot/dht.save.bin"

[Dashboard]

; time in seconds for a refresh, from 2 to 20
RefreshPeriod = 10
; maximum number of last heard rows to show, from 1 to 100
LastHeardSize = 20

; there are multiple sections of the dashboard:
; IP is the IP Address Section (shows local and external IPs)
; LH is the Last Heard Section
; LS is the Linked Reflector Status
; MS is the CC1200 Modem Status (how it's configured)
; SY is the System Section, (RPi and mspot info)
ShowOrder = "LS,LH,SY"  ; Don't use spaces in the order
